development:
  adapter: postgresql
  encoding: unicode
  database: myapp_development11
  pool: 5
  username: myapp
  password: password1

test:
  adapter: postgresql
  encoding: unicode
  database: myapp_test11
  pool: 5
  username: myapp
  password: password1
